FROM python:3.9-alpine

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

ENV APP_HOME /app
WORKDIR $APP_HOME

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt $APP_HOME/requirements.txt
RUN pip install -r requirements.txt
RUN pip install black flake8

EXPOSE 8000

COPY . $APP_HOME/